services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    networks:
      - library
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:${DB_PORT}'
    env_file:
    - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql

  app:
    image: sergiozeppo/nodejs2025q2-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - library
    ports:
      - '4000:${PORT}'
    env_file:
    - .env
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_NAME:  ${DB_DATABASE}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
    name: library-postgres-data
  postgres_logs:
    name: library-postgres-logs

networks:
  library:
    driver: bridge
    name: home-library