services:
  app:
    build: .
    image: sergiozeppo/nodejs2025q2-service-app:latest
    ports:
      - "${PORT}:${PORT}" 
    environment:
      - PORT=${PORT}
      - DB_HOST=db
      - DB_PORT=${PG_PORT}
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASSWORD}
      - DB_NAME=${PG_DB}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "${PG_PORT}:${PG_PORT}"
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql/

volumes:
  pgdata:
  pglogs:

networks:
  app-network:
    driver: bridge